[SilentPatch]
; Allows to override units used by the game - 0 forces metric units, 1 forces imperial units,
; -1 makes the game use units based on system locale
Units=-1
; Enables fixes for corona placements on emergency vehicles and taxis
; This fixes siren placements on Police, Enforcer, Firetruck, Ambulance, FBI Rancher and Vice Cheetah,
; it also adds a siren to FBI Washington, corrects taxi sign light placement on Taxi
; and fixes placement of the search light and rear rotor light on Police Maverick.
EnableVehicleCoronaFixes=1
; Enables an unfinished "minimal HUD" feature, where health, armour, weapon and money UI elements
; fade out when inactive.
MinimalHUD=0
; Enables the sliding mission title text, based on remnants of this feature in the game code.
SlidingMissionTitleText=0
; Enables the sliding odd job text, based on remnants of this feature in the game code.
; This behaviour was visible in one of the beta clips released for GTA III.
SlidingOddJobText=0
; Enables a map blip for properties available to purchase. They were always created by the mission script,
; but did not show on the map.
ShowPropertyBlips=0
; By default, SilentPatch shrinks the radar disc texture by 2px to avoid gaps between the map and the disc.
; However, this may introduce issues with custom radar disc textures, for example the PS2 texture.
; With this option, you may opt-out of shrinking.
DontShrinkRadardisc=0
; Use the desktop refresh rate instead of a forced 60Hz while in fullscreen mode. This will get rid of
; a flicker when starting the game on a high refresh rate display.
UseDesktopRefreshRate=1
; Makes the script sprites scale to resolution. Disable only if you use CLEO mods that are aware of this issue
; and do the scaling themselves, to avoid double-scaling.
ScaleScriptSprites=1
; Speech Delay Timer (in ms)
; Adjust the delay time between NPC comments
; Set -1 to make the game use default delay time (6000ms)
SpeechDelayTimer=0

[ExtraCompSpecularityExceptions]
; Put model IDs or names (one ID/name per line) here to forcibly disable specularity on their extras
; Since SilentPatch applies proper environment maps on extras, specularity misconfigurations result
; in all extras being shiny, even if they are obviously meant not to be metallic.

; By default we exclude Stallion and Mesa Grande because of their leather roofs
stallion
mesa

[DrawBackfaces]
; Models on this list will draw with backface culling disabled, like DrawBackfaces.txt from the mobile versions
; Put model IDs or names (one ID/name per line)
4x4racecotop2
4x4signstop
ammu_windows1
ap_barriergate1
ap_barriergate2
ap_barriergate3
ap_billboards1
ap_billboards2
ap_billboards3
ap_gatesA
ap_gatesB
ap_hookerinn1
ap_hotelpool
ap_roadsigns1_02
ap_seahangstuft
ap_seaplanedock1
ap_stairsout04
ap_wallfence5
basketballcourt05
bb_pooltable1_01
biker_bar_exterior
bikeshop_glass2
BillBd04
BillBd1
BillBd2
BillBd3
bnk_main_rework
bnk_man_ofc
bnk_man_ofc01
bodyarmour
bouy
buldingsite1
carsontrack
car_fucko03
chairsntable
chairsntableml
ci_alights1_01
ci_astudlights
ci_backlot1
ci_backlot2
ci_backlot3
ci_backlotprops1
ci_backlotprops2
ci_backlotprops3
ci_blights1_01
ci_camera1_01
ci_extertank
ci_flatprop01
ci_flatprop02
ci_fountain
ci_industrial1
ci_lander
ci_lights1_01
ci_manintstuff
ci_mansion1
ci_offices
ci_pornset1
ci_redhead1_01
ci_tankship
ci_watertank
ci_windmach
club_exterior06
cl_curtains
cl_tbl_chait_tmp
cl_tbl_chait_tmpb
cl_yachtmdl
cof_bardetail
cof_extwindw
concerth06
concerth07
concerth08
concerth10
concerth12
concerth27
concerth29
concerth56
cop_mainroom
deco_polbuild
deli_exterior_front
destruct03
destruct04
destruct05
destruct1
destruct2
dk_paynspray
docks10rail
docks40
docksware01
doc_crane_cab04
doontoon32
doontoon54
doontoon65
doontoon_22_b
doontoon_shops
doontoon_top03
doontoon_top06
doontoon_top07
doublestreetlght1
dow_pizzaplacedt
drugstoreext
drugstoreint
fence01
fire_hydrant
fuckedcars01
fuckedcars02
fuckedcars03
fuckedcars04
fuckedcars05
fuckedcars06
ggneonsign2
haitgangshop
haiticar08
haiticar09
haiticar10
haiticar12
haiticar13
hai_houses27
havbuild
hav_car_show_out
hav_car_show_out2
hogans_alley_b
hospital
hot_room317
hot_trans1
htl_dco_chair03_dy
htl_dco_chair03_nt
ht_kb_couch1_dy
ht_kb_couch1_nt
ht_mainfloor_dy
ht_mainfloor_nt
instruments
kb_chr_tbl_test
kickbannerstart01
kickbus03
kickcar06
kickcar17
kickcar23
kickcar28
kickcar3
kickcar36
lampost_coast
lamppost1
lamppost2
lamppost3
lhaitnewbt
lha_carfence
lhbuild034
lhcargo
lhroofst01
lhroofst18
lh_buildingg1
lh_buildingg3
lh_icecream02
lh_misc02
lh_philsext
lh_philsint
lh_pizzaplace
lh_taxifirm01
litharoada2
litharoada3
lithit14
lithitsjm
loopbig
looplop2
lw_lights
lw_roombitsb
MALLUNDER
mall_ammu
mall_ammuwin
;mall_hardware
manmrgbase1
mansion1b
mansion1gardens
Mansion2c
mansion2_b
mansion3a
mans_merge03
man_backside
man_backside2
man_build03
man_frntstepGD
man_monitor_base
miamiland037
miamiland170
miamiland172
miamiland174
miamiland179
miamiland180
mlamppost
mlnorthmalllftex
mlobjects_n
mlrecords
ml_cofcounter1
ml_coffee_dsk
ml_gap
ml_jewellers
ml_planterbed
ml_record
mob_mobroom2
MTraffic1
MTraffic2
MTraffic3
MTraffic4
nbchwbridge
nbdecoshop01
nbecland09
nbec_divingbds
nbhotel02
nbhotel08
nbnorthmallext1
nbtgardoor
nbtshopfronts01
nbt_apartpool01
nbt_apartpool02
nbt_apartpool03
nbt_balcony02
nbt_balcony03
nbt_balcony05
nbt_hotel01
nbt_hotel06balcony
nbt_htlpiswr01
nbt_htlpiswr02
nbt_htlpoolbar01
nbt_pizzaplace
nbt_rooftopstart
newbuild01
nhaiticar13
nmalloutside
npw_press1_02
oceanroad04
od_bighotcons
od_bighotpool
od_chariot
od_clevelander_dy
od_clevelander_nt
od_clubneon
od_divingbds
od_lightbeam
od_lightext
od_lightint
od_pelican2_nt
od_pelican_nt
od_walkway2
od_walkway3
od_wtlegs
parktable1
plank1
plankk2
poolwaterwshs
pot_02
pw_priint
rafelneonsgn
RoosbrgeStart_r_dt
RoosbrgeStart_r_nt
scarinterior1
seveneleven
shpfrnts03rail02
sjmbigsig
sjmbigsig2
sjmbigsign01
sjmbigsign02
sjmcoast
sjmfsthus
sjmhoose
sjmkhus
spad_water
spad_watr1
starbits06
starbits17
starbits22
starbits24
starbits49
starbits50
starbits51
starblocks03
stObject23
stPOOLw1
stpoolwater
stPOOLWATER02
stPOOLWATER5
streetlamp1
streetlamp2
stripback
stripinterupside
strpclubsigns1
telgrphpole02
trafficlight1
washbuild018
washbuild030
washbuild033
washbuild200
washbuild206
washgasneon
washgasneon01
washgasneon02
washgaspump
washmallwater
washotelneon1
wash_ammu
wash_hardwares
wash_hardwindow
woshmalneon2
wshbuildws06
wshbuildws20
wshbuildws38
wshbuildws40
wshhotelwater1
wshmallneon
wshnrthpstr02
wshnrthpstr03
wshnrthpstr05
wshnrthpstr07
wshnrthpstr1
wshsthpstr02
wshsthpstr04
wshsthpstr05
wshxrefhirise1
wshxrefhse2

[DontDrawBackfaces]
; Models on this list will draw with backface culling ENABLED, even if they should otherwise have BFC off.
; This is useful e.g. if backface culling breaks specific modded character skins.
; Put model IDs or names (one ID/name per line)
