; Framerate Vigilante Mod by Junior_Djjr - MixMods.com.br
[Settings]

; (default: 30) FPS limit when limiter is turned on. Other mods like MixSets also changes this.
; Avoid using more than 60 FPS.
FPSlimit = 60
